version: "3"
services:
  vote:
    image: rq170/vote:1.0.4
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

      restart_policy:
        condition: on-failure

    ports:
      - "8075:80"

    networks:
      - webnet

networks:
  webnet:

