version: "3"
services:

  x47b:
    # replace username/repo:tag with your name and image details
    image: rq170/x47b:1.0.0
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.4"
          memory: 350M

      restart_policy:
        condition: on-failure

    ports:
      - "8082:80"

    networks:
      - webnet

networks:
  webnet:

